[package]
name = "pile"
version = "0.1.0"
authors = ["Clement Lee <2158058+clementlee@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4"
sha2 = "0.9.2"
